### ISSUE TITLE
Does not watch pyproject.toml changes

### ISSUE THREAD

**Issue by mecampbellsoup** [olzhasar/pytest-watcher#39]
Hello,

I have the following config in my `pyproject.toml`:

```toml
[tool.pytest-watcher]
now = true
clear = true
delay = 0.2
runner = "pytest"
runner_args = []
patterns = ["*.py", "pyproject.toml"]
```

When I start with `ptw . -n0`, changes to `.py` files are watched and the test process restarts as desired. But changes to the `pyproject.toml` configuration does not trigger restart.

The docs explicitly give the example of modifying `--patterns = '*.py,pyproject.toml'` so I'm assuming what I'm trying to do is supported behavior, correct?
